USE [master]
GO

/****** Object:  Database [ordersystem]    Script Date: 17/09/2024 02:06:37 ******/
CREATE DATABASE [ordersystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ordersystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ordersystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ordersystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ordersystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ordersystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ordersystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ordersystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ordersystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ordersystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ordersystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [ordersystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ordersystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ordersystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ordersystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ordersystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ordersystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ordersystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ordersystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ordersystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ordersystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ordersystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ordersystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ordersystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ordersystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ordersystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ordersystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ordersystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ordersystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ordersystem] SET  MULTI_USER 
GO

ALTER DATABASE [ordersystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ordersystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ordersystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ordersystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ordersystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ordersystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ordersystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ordersystem] SET  READ_WRITE 
GO


